@extends('ecommerce.layouts.app')

@section('content')
    @php $paymentQrUrl = ! empty($business['payment_qr_url']) ? $business['payment_qr_url'] : null; @endphp
    <style>
        .checkout-layout { display:grid; grid-template-columns:minmax(0, 1.35fr) minmax(280px, .75fr); gap:24px; align-items:start; }.checkout-summary { position:sticky; top:96px; }.checkout-items { margin-top:14px; }.checkout-item { padding:11px 0; border-bottom:1px solid var(--shop-line); display:flex; justify-content:space-between; gap:14px; color:var(--shop-ink); font-size:13px; }.checkout-item small { color:var(--shop-ink-soft); }.checkout-qr { width:160px; border:1px solid var(--shop-line); border-radius:6px; cursor:zoom-in; } @media(max-width:900px){.checkout-layout{grid-template-columns:1fr}.checkout-summary{position:static}}
    </style>
    <section class="shop-page">
        <header class="shop-page-header"><div><div class="shop-page-header__eyebrow">Ultimo paso</div><h1>Finalizar compra</h1><p>Completa los datos para enviar tu pedido.</p></div><a href="{{ route('shop.cart') }}" class="shop-action shop-action--soft">Volver al carrito</a></header>
        <div class="checkout-layout">
            <section class="shop-surface"><h2>Datos del pedido</h2>
                @if ($isRestaurantCatalog)<div class="shop-notice">Tu pedido sera revisado antes de pasar a preparacion.</div>@endif
                <div class="shop-notice">El pedido se registra de inmediato. Las transferencias y pagos QR se confirman despues de validar la referencia.</div>
                <form method="POST" action="{{ route('shop.place-order') }}" class="shop-form-grid">@csrf
                    <div class="shop-field"><label>Nombre</label><input class="shop-input" value="{{ auth()->user()->name }}" disabled></div>
                    <div class="shop-field"><label>Correo electronico</label><input class="shop-input" value="{{ auth()->user()->email }}" disabled></div>
                    <div class="shop-field"><label for="phone">Telefono</label><input id="phone" name="phone" class="shop-input" value="{{ old('phone', $customer->phone) }}" placeholder="Ej: 300 123 4567"></div>
                    @if ($isRestaurantCatalog)<div class="shop-field"><label for="fulfillment_type">Tipo de pedido</label><select id="fulfillment_type" name="fulfillment_type" class="shop-input"><option value="delivery" @selected(old('fulfillment_type', 'delivery') === 'delivery')>Domicilio</option><option value="takeaway" @selected(old('fulfillment_type') === 'takeaway')>Para llevar</option></select></div>@endif
                    <div class="shop-field shop-field--full"><label for="address">Direccion de entrega</label><input id="address" name="address" class="shop-input" required value="{{ old('address', $customer->address) }}" placeholder="Ej: Calle 123 # 45-67, apartamento 201"></div>
                    <div class="shop-field"><label for="payment_method">Metodo de pago</label><select id="payment_method" name="payment_method" class="shop-input" required><option value="transfer" @selected(old('payment_method', 'transfer') === 'transfer')>Transferencia bancaria</option><option value="contraentrega" @selected(old('payment_method') === 'contraentrega')>Contraentrega</option>@if ($paymentQrUrl)<option value="qr" @selected(old('payment_method') === 'qr')>QR</option>@endif</select></div>
                    <div class="shop-field"><label for="coupon_code">Cupon</label><input id="coupon_code" name="coupon_code" class="shop-input" value="{{ old('coupon_code') }}" placeholder="Ej: BIENVENIDO10"></div>
                    <div class="shop-field" id="payment-reference-wrapper"><label for="payment_reference">Referencia reportada</label><input id="payment_reference" name="payment_reference" class="shop-input" value="{{ old('payment_reference') }}" placeholder="Ej: TRX-123456"><div class="shop-note">Aplica para transferencia o QR.</div></div>
                    <div class="shop-field shop-field--full"><label for="customer_note">Nota del pedido</label><input id="customer_note" name="customer_note" class="shop-input" value="{{ old('customer_note') }}" placeholder="Indicaciones de entrega (opcional)"></div>
                    @if ($paymentQrUrl)<div class="shop-field shop-field--full d-none" id="payment-qr-wrapper"><div class="shop-notice"><strong>Pago por QR</strong><div class="shop-note">Escanea el codigo y registra la referencia de tu pago.</div><img src="{{ $paymentQrUrl }}" alt="QR de pago" class="checkout-qr js-qr-trigger mt-2"></div></div>@endif
                    <div class="shop-field shop-field--full"><button type="submit" class="shop-action w-100">Enviar pedido</button></div>
                </form>
            </section>
            <aside class="shop-summary checkout-summary"><h2>Resumen</h2><div class="checkout-items">@foreach ($cartItems as $item)<div class="checkout-item"><span>{{ $item['display_name'] }} x {{ $item['quantity'] }}@if(!empty($item['selection_summary']))<small class="d-block">@foreach($item['selection_summary'] as $line){{ $line['group'] }}: {{ implode(', ', $line['labels']) }}@endforeach</small>@endif</span><strong>COP {{ number_format($item['total'], 2) }}</strong></div>@endforeach</div><div class="shop-totals"><div class="shop-total-row"><span>Subtotal</span><strong>COP {{ number_format($summary['subtotal'], 2) }}</strong></div><div class="shop-total-row"><span>Impuestos</span><strong>COP {{ number_format($summary['tax'], 2) }}</strong></div><div class="shop-total-row shop-total-row--final"><span>Total</span><strong>COP {{ number_format($summary['total'], 2) }}</strong></div></div></aside>
        </div>
    </section>
    <script>(function(){const m=document.getElementById('payment_method'),f=document.getElementById('fulfillment_type'),q=document.getElementById('payment-qr-wrapper'),r=document.getElementById('payment-reference-wrapper'),i=document.getElementById('payment_reference'),a=document.getElementById('address');if(!m||!r||!i)return;const payment=()=>{const show=m.value==='transfer'||m.value==='qr';r.classList.toggle('d-none',!show);i.required=show;if(q)q.classList.toggle('d-none',m.value!=='qr');if(!show)i.value=''};const fulfillment=()=>{if(!f||!a)return;const take=f.value==='takeaway';a.required=!take;a.placeholder=take?'No requerida para pedidos para llevar':'Direccion de entrega';if(take)a.value=''};m.addEventListener('change',payment);f?.addEventListener('change',fulfillment);payment();fulfillment()})();</script>
@endsection
